#!/usr/bin/env bash
# Regenerate the protobuf artifacts for the foxglove.CompressedImage image
# channel. Run this after editing proto/foxglove/CompressedImage.proto.
#
# Produces (vendored into the repo, so the example builds with only the
# protobuf runtime and no protoc at build time):
#   src/generated/foxglove/CompressedImage.pb.{h,cc}   -- C++ message classes
#   src/generated/foxglove_schema.hpp                  -- base64(FileDescriptorSet)
#
# Requires: protoc (protobuf-compiler), base64 (coreutils).
set -euo pipefail

cd "$(dirname "$0")/.."

PROTO=proto/foxglove/CompressedImage.proto
GEN=src/generated
mkdir -p "$GEN/foxglove"

# 1. C++ message classes (namespace foxglove).
protoc --proto_path=proto --cpp_out="$GEN" "$PROTO"

# 2. FileDescriptorSet -> base64 -> header. Foxglove's `schema` field for a
#    protobuf channel is exactly this base64 string.
protoc --proto_path=proto --descriptor_set_out="$GEN/foxglove.desc" "$PROTO"
{
  printf '// AUTO-GENERATED by scripts/regenerate_proto.sh — do not edit.\n'
  printf '// Base64 of the FileDescriptorSet for %s.\n' "$PROTO"
  printf '#pragma once\n\nnamespace foxglove_schema {\n'
  printf 'constexpr const char* kCompressedImage =\n    "'
  base64 -w0 "$GEN/foxglove.desc"
  printf '";\n}  // namespace foxglove_schema\n'
} > "$GEN/foxglove_schema.hpp"
rm -f "$GEN/foxglove.desc"

echo "regenerated: $GEN/foxglove/CompressedImage.pb.{h,cc}, $GEN/foxglove_schema.hpp"
