# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: record_image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'record_image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12record_image.proto\x12\x0e\x61viator.record\"\xf2\x01\n\nImageFrame\x12\x14\n\x0cpublisher_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x11\n\tcamera_id\x18\x03 \x01(\t\x12\x10\n\x08\x66rame_id\x18\x04 \x01(\x04\x12\x16\n\x0esample_mono_us\x18\x05 \x01(\x04\x12\x10\n\x08\x63lock_id\x18\x06 \x01(\t\x12\r\n\x05width\x18\x07 \x01(\r\x12\x0e\n\x06height\x18\x08 \x01(\r\x12\x14\n\x0cpixel_format\x18\t \x01(\t\x12\x10\n\x08\x65ncoding\x18\n \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x0b \x01(\x0c\x12\x16\n\x0e\x63\x61libration_id\x18\x0c \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'record_image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFRAME']._serialized_start=39
  _globals['_IMAGEFRAME']._serialized_end=281
# @@protoc_insertion_point(module_scope)
