if(AVIATOR_COMMUNICATION_ONLY OR NOT AVIATOR_BUILD_ROBOTICS_LIBS)
  return()
endif()
if(AVIATOR_BUILD_XCORE_SDK)
  add_library(aviator_manipulator_sdk SHARED rokae_sdk.cpp)
  target_include_directories(aviator_manipulator_sdk PRIVATE ${AVIATOR_VENDOR_DIR}/xCoreSDK-0.7.1/include)
  target_link_libraries(aviator_manipulator_sdk PRIVATE aviator_logging Eigen3::Eigen Rokae::Rokae Threads::Threads ${CMAKE_DL_LIBS})
  target_link_options(aviator_manipulator_sdk PRIVATE "-Wl,--exclude-libs,ALL" "-Wl,-Bsymbolic")
  add_library(aviator_device STATIC DataLink_rokae.cpp)
  target_include_directories(aviator_device PUBLIC ${PROJECT_SOURCE_DIR}/common/include)
  target_link_libraries(aviator_device PUBLIC aviator_robotics_deps Threads::Threads)
  target_link_libraries(aviator_device PRIVATE aviator_manipulator_sdk aviator_logging)
  target_compile_definitions(aviator_device PUBLIC AVIATOR_HAVE_ROKAE=1)
  install(TARGETS aviator_manipulator_sdk LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})
  add_executable(manipulator main.cpp)
  target_link_libraries(manipulator PRIVATE aviator_device aviator_device_server aviator_core_control)
  install(TARGETS manipulator RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
endif()
